### ISSUE TITLE
brew fails, does not exist

### ISSUE THREAD

**Issue by lescar** [Dashlane/dashlane-cli#100]
brew update
Already up-to-date.

brew install --build-from-source dashlane-cli.rb
Running `brew update --auto-update`...
[...]
Warning: No available formula with the name "dashlane-cli.rb".
==> Searching for similarly named formulae and casks...
==> Casks
dashcam-viewer

To install dashcam-viewer, run:
  brew install --cask dashcam-viewer

![image](https://user-images.githubusercontent.com/3657582/235584983-e5ed2a77-cd15-4e9e-8e99-70e0ae58df25.png)

**Comment by BenjaminOddou** [comment]
Dashlane-cli is not yet in brew. See [here](https://github.com/Homebrew/homebrew-core/pull/124525). The build from source uses a local ruby script to install the cli. I made one for the v1.7.0 because the one in this repo is not up to date. See [here](https://github.com/BenjaminOddou/alfred-dashlane/blob/main/src/dashlane-cli.rb).

**Comment by Mikescops** [comment]
The ruby script has been updated in the repository too.
You must run the command in the repository folder.

**Comment by BenjaminOddou** [comment]
Hope the cli will be available in homebrew 🤞

**Comment by Mikescops** [comment]
For now I have abandoned the idea because their CI is very crappy and they don't want to fix it. I'll probably provide a tap in this repo/org later.

**Comment by BenjaminOddou** [comment]
Yes I followed the thread and it seems kind of complicated to integrate the cli with their actual system. They didn't seems to wanna help which is a bit disappointing IMO.
