### ISSUE TITLE
Unwanted Dashlane CLI keychain passwords on MacOS

### ISSUE THREAD

**Issue by BenjaminOddou** [Dashlane/dashlane-cli#55]
Hello,

after doing some auth tests with the CLI, I found out that for each connexion attempt, the CLI creates a certificate. Maybe moving the creation of this certificate after the user is connected could be a nice feature.

![test](https://user-images.githubusercontent.com/85166574/220598391-734be41f-f5dd-4bcd-8650-d2cfe547fb2b.png)

**Comment by Mikescops** [comment]
Hello,
At which step do you stop? There are multiple steps in the authentication process and the local password is required quite early in the process to protect some pwd.

**Comment by BenjaminOddou** [comment]
Hello @Mikescops,

I stopped after entering the mail. In the screenshot the account is `test` which is not a valid email but it still creates a keychain password in that case.

**Comment by Mikescops** [comment]
Oh ok, I'll have a deeper look then, thanks!

**Comment by jboillot** [comment]
Hello!

The reason for accessing the OS keychain before the first login is that we didn't want users to go through the whole login process, and at the end get an error, which would force them to start over again from the beginning.

However, it should be possible to postpone the keychain access, save the local key encrypted using the master password in the DB, and display a warning instead of an error if the keychain is unreachable.

What is your opinion about that @Mikescops ?

**Comment by Mikescops** [comment]
Looks good to me!
