### ISSUE TITLE
on linux, the the clipboard is cleared after application exit

### ISSUE THREAD

**Issue by jbatesy** [Dashlane/dashlane-cli#87]
For some reason the clipboard is cleared on Linux systems after closing

I know this ticket is lacking detail, I am doing some investigation. It looks like its a thing with X11... the clipboard is maintained by the process, so once its terminated the clipboard is "gone"

**Comment by jbatesy** [comment]
Looks like the best solution would be to add an option so dashlane-cli can sleep when using the clipboard option... working on a PR

**Comment by jboillot** [comment]
Hello,

This issue is related to this one: https://github.com/1Password/arboard/issues/39. This is because you are not using a clipboard manager. I suggest you install one, or you use a desktop environment that implements one by default, like GNOME with mutter.

If you tell me the desktop environment you are using I could try to help you.
I'm afraid the pull request you offered won't be accepted because solving a niche problem.

Nevertheless, thanks for your investigations :)

**Comment by jboillot** [comment]
After some investigation on a Xubuntu VM I have found a working setup: it uses the clipboard manager diodon (so first `sudo apt purge xfce4-clipman && sudo apt install diodon`). At this point, you may have to restart your system (or `killall xfce4-clipman && diodon`).
Then you have to modify the diodon preferences so it uses the primary selection like in the following image, et voilà!

![image](https://user-images.githubusercontent.com/52931370/227229902-e8616a60-db42-40d5-b7d1-433e82168038.png)

Please tell me if it still doesn't work!

**Comment by jbatesy** [comment]
@jboillot thank you for going through the trouble to investigate this for me, no worries regarding the PR, it was good practice anyway.

Your suggestion works perfectly, although there is no need for the Use primary selection option, that just puts the text you select with your cursor into the clipboard manager. Keep clipboard content is the option that does what we are looking for.

Closing this issue off now.
